#!/usr/bin/env node

/**
 * Git Hook Version of Commit Message Suggester
 * This version writes suggestions to the commit message file
 * Used by prepare-commit-msg hook
 */

import * as fs from 'fs';
import * as path from 'path';

import { AIClientFactory } from './ai/client-factory.js';
import { GitDiffAnalyzer } from './utils/git-diff-analyzer.js';
import { logger } from './utils/logger.js';

async function main() {
  try {
    const commitMsgFile = process.argv[2];
    
    if (!commitMsgFile) {
      console.error('Usage: suggest-commit-hook <commit-msg-file>');
      process.exit(1);
    }

    // Priority 1: Use environment variables (like GitHub Actions)
    // Priority 2: Load from ~/.bob-pr-reviewer/.env if it exists
    // This allows users to set secrets in their shell profile instead of .env
    
    if (!process.env.AI_PROVIDER && !process.env.OPENAI_API_KEY && !process.env.ANTHROPIC_API_KEY) {
      // No env vars set, try loading from .env file
      const homeDir = process.env.HOME || process.env.USERPROFILE || '';
      const envPath = path.join(homeDir, '.bob-pr-reviewer', '.env');
      
      if (fs.existsSync(envPath)) {
        const dotenv = await import('dotenv');
        dotenv.config({ path: envPath });
      }
    }

    // Step 1: Analyze staged changes
    const analyzer = new GitDiffAnalyzer();
    const diffSummary = await analyzer.analyzeStagedChanges();

    // Step 2: Get AI client
    const config = AIClientFactory.getConfigFromEnv();
    const aiClient = AIClientFactory.createClient(config);

    // Check if client supports commit message generation
    if (!aiClient.generateCommitMessage) {
      // Silently skip if not supported
      process.exit(0);
    }

    // Step 3: Generate commit message suggestions
    const result = await aiClient.generateCommitMessage(diffSummary);

    if (!result.suggestions || result.suggestions.length === 0) {
      process.exit(0);
    }

    // Step 4: Format suggestions as comments in commit message file
    const suggestions = result.suggestions.map((suggestion, index) => {
      const scope = suggestion.scope ? `(${suggestion.scope})` : '';
      const breaking = suggestion.breaking ? '!' : '';
      const subject = `${suggestion.type}${scope}${breaking}: ${suggestion.subject}`;
      
      let formatted = `# ${index + 1}. ${subject}`;
      if (suggestion.body) {
        formatted += `\n#    ${suggestion.body.replace(/\n/g, '\n#    ')}`;
      }
      formatted += `\n#    Confidence: ${suggestion.confidence}`;
      if (suggestion.breaking) {
        formatted += '\n#    ⚠️  BREAKING CHANGE';
      }
      
      return formatted;
    }).join('\n#\n');

    // Step 5: Read existing commit message file
    let existingContent = '';
    if (fs.existsSync(commitMsgFile)) {
      existingContent = fs.readFileSync(commitMsgFile, 'utf-8');
    }

    // Step 6: Prepare new content with AI suggestions
    const header = `# 🤖 AI-Generated Commit Message Suggestions
# 
# Choose one of the suggestions below by uncommenting it (remove the #)
# or write your own commit message above this section.
#
# Generated by ${config.provider} | ${new Date().toISOString()}
#
`;

    const footer = `#
# ────────────────────────────────────────────────────────────
# To use a suggestion:
#   1. Uncomment one of the suggestions above (remove the #)
#   2. Or write your own message at the top
#   3. Save and close this file
#
# Token-optimized analysis used ~${result.metadata.tokensUsed || 'N/A'} tokens
# ────────────────────────────────────────────────────────────
`;

    const newContent = header + suggestions + '\n' + footer + '\n' + existingContent;

    // Step 7: Write to commit message file
    fs.writeFileSync(commitMsgFile, newContent, 'utf-8');

    // Success - exit silently
    process.exit(0);

  } catch (error: any) {
    // Log error but don't block the commit
    logger.error('Commit message suggestion failed:', error);
    
    // Write a simple comment to the commit message file
    const commitMsgFile = process.argv[2];
    if (commitMsgFile && fs.existsSync(commitMsgFile)) {
      const existingContent = fs.readFileSync(commitMsgFile, 'utf-8');
      const errorMsg = `# ⚠️  AI commit message suggestion failed: ${error.message}\n# Please write your commit message manually.\n\n`;
      fs.writeFileSync(commitMsgFile, errorMsg + existingContent, 'utf-8');
    }
    
    // Exit successfully to not block the commit
    process.exit(0);
  }
}

main();